# Generated by Django 3.0.5 on 2020-05-04 00:28

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_refactored_profiles_to_separate_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="date_last_tested_negative",
            field=models.DateField(
                verbose_name="Date Last Tested Negative for COVID19 "
            ),
        ),
        migrations.AlterField(
            model_name="donorprofile",
            name="igg_report",
            field=models.FileField(
                upload_to="igg_donor_reports",
                validators=[profiles.validators.validate_file_extension],
                verbose_name="Immunoglobulin G (IgG) Test Report",
            ),
        ),
        migrations.AlterField(
            model_name="donorprofile",
            name="last_covid_report",
            field=models.FileField(
                null=True,
                upload_to="last_donor_reports",
                validators=[profiles.validators.validate_file_extension],
                verbose_name="Last COVID19 Negative Test Report",
            ),
        ),
        migrations.AlterField(
            model_name="donorprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Your Location (It will be kept confidential)"
            ),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="contact_person_mobile_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.",
                        regex="^\\+?91?\\d{9,10}$",
                    )
                ],
                verbose_name="Contact Number (+91xxxxxxxxxx)",
            ),
        ),
        migrations.AlterField(
            model_name="hospitalprofile",
            name="contact_person_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Contact Person Name"
            ),
        ),
    ]
