# Generated by Django 2.2 on 2020-04-19 06:58

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Your Location (It will be kept confidential)'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital_address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Exact Hospital Address'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Hospital Location '),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='mci_registeration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medical Counsel of India Registration Number'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.", regex='^\\+?91?\\d{9,10}$')], verbose_name='Contact Number'),
        ),
    ]
