# Generated by Django 2.2 on 2020-04-19 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.", regex='^\\+?91?\\d{9,10}$')], verbose_name='Contact Number (+91xxxxxxxxxx)'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital_address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Hospital Address'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.", regex='^\\+?91?\\d{9,10}$')], verbose_name='Contact Number (+91xxxxxxxxxx)'),
        ),
    ]
