# Generated by Django 3.0.5 on 2020-04-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_igg_report_and_recovery_date_donor_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
        migrations.AddField(
            model_name="donorprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="donorprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Last Name"
            ),
        ),
    ]
