# Generated by Django 2.2 on 2020-04-25 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=200, verbose_name="Question")),
                ("response", models.TextField(max_length=200, verbose_name="Answer")),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.",
                                regex="^\\+?91?\\d{9,10}$",
                            )
                        ],
                        verbose_name="Contact Number (+91xxxxxxxxxx)",
                    ),
                ),
                ("query", models.TextField(max_length=200, verbose_name="Query")),
                (
                    "date",
                    models.DateTimeField(auto_now=True, verbose_name="Recorded at "),
                ),
            ],
        ),
    ]
