# Generated by Django 2.2 on 2020-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(max_length=1000, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="response",
            field=models.TextField(max_length=1000, verbose_name="Answer"),
        ),
    ]
