# Generated by Django 3.0.5 on 2020-05-03 23:58

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0008_refactored_profiles_to_separate_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last Name"),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Your Location (It will be kept confidential)",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Date of Birth")),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        help_text="Format (+91xxxxxxxxxx)",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.",
                                regex="^\\+?91?\\d{9,10}$",
                            )
                        ],
                        verbose_name="Contact Number",
                    ),
                ),
                (
                    "last_covid_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="last_donor_reports",
                        validators=[profiles.validators.validate_file_extension],
                        verbose_name="Last COVID19 Negative Test Report",
                    ),
                ),
                (
                    "date_last_tested_negative",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Last Tested Negative for COVID19 ",
                    ),
                ),
                (
                    "igg_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="igg_donor_reports",
                        validators=[profiles.validators.validate_file_extension],
                        verbose_name="Immunoglobulin G (IgG) Test Report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "hospital_name",
                    models.CharField(max_length=100, verbose_name="Hospital Name"),
                ),
                (
                    "hospital_address",
                    models.CharField(max_length=500, verbose_name="Hospital Address"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Hospital Location "
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Contact Person Name",
                    ),
                ),
                (
                    "contact_person_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 9-10 digits allowed.",
                                regex="^\\+?91?\\d{9,10}$",
                            )
                        ],
                        verbose_name="Contact Number (+91xxxxxxxxxx)",
                    ),
                ),
                (
                    "mci_registration_number",
                    models.CharField(
                        max_length=50,
                        verbose_name="Medical Counsel of India Registration Number",
                    ),
                ),
            ],
        ),
    ]
