# Generated by Django 3.0.7 on 2020-06-16 22:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_patient_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="document_of_proof",
            field=models.FileField(
                default="",
                help_text="This can be your doctor's prescription or a COVID19 test report or any other valid document",
                upload_to="patient_authentication",
                validators=[profiles.validators.validate_file_extension],
                verbose_name="Document for Authentication",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="hospital_name_and_address",
            field=models.CharField(
                default="",
                max_length=500,
                verbose_name="Name and Address of Hospital admitted in",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326,
                verbose_name="Your Location / Hospital's Location (It will be kept confidential)",
            ),
        ),
    ]
